"""
示例项目数据
"""

SAMPLE_PROJECTS = [
    # 流动性质押
    {
        "name": "Lido Finance",
        "slug": "lido-finance",
        "category": "liquid-staking",
        "logo_url": "https://icons.llama.fi/lido.png",
        "website": "https://lido.fi",
        "contract_address": "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84",
        "defillama_id": "lido",
        "description": "Lido 是最大的以太坊流动性质押协议，允许用户质押 ETH 获得 stETH，同时保持资产流动性。",
        "tokens": [
            {"symbol": "stETH", "address": "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"},
            {"symbol": "LDO", "address": "0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32"},
        ],
        "overall_score": 85,
        "score_details": {
            "contract_security": {"score": 90, "weight": 35, "factors": ["多次审计", "开源代码", "Bug Bounty"]},
            "team": {"score": 85, "weight": 25, "factors": ["团队公开", "知名投资机构"]},
            "tokenomics": {"score": 80, "weight": 20, "factors": ["LDO 治理代币", "分配合理"]},
            "operation": {"score": 85, "weight": 20, "factors": ["TVL 最大", "用户活跃"]},
        },
        "risk_warnings": ["注意 Slashing 风险", "stETH 可能短期脱锚"],
        "summary": "Lido 是最大的 ETH 质押协议，经过多次审计，安全性较高，但需注意 Slashing 风险和 stETH 脱锚风险。",
        "source_links": [
            {"type": "audit", "title": "审计报告", "url": "https://github.com/lidofinance/audits"},
            {"type": "docs", "title": "官方文档", "url": "https://docs.lido.fi"},
        ],
        "status": "published",
        "is_featured": True,
        "display_order": 1,
    },
    {
        "name": "Rocket Pool",
        "slug": "rocket-pool",
        "category": "liquid-staking",
        "logo_url": "https://icons.llama.fi/rocket-pool.png",
        "website": "https://rocketpool.net",
        "contract_address": "0xae78736Cd615f374D3085123A210448E74Fc6393",
        "defillama_id": "rocket-pool",
        "description": "Rocket Pool 是去中心化的以太坊质押协议，支持节点运营商和普通用户参与质押。",
        "tokens": [
            {"symbol": "rETH", "address": "0xae78736Cd615f374D3085123A210448E74Fc6393"},
            {"symbol": "RPL", "address": "0xD33526068D116cE69F19A9ee46F0bd304F21A51f"},
        ],
        "overall_score": 82,
        "score_details": {
            "contract_security": {"score": 88, "weight": 35, "factors": ["多次审计", "去中心化设计"]},
            "team": {"score": 80, "weight": 25, "factors": ["团队公开"]},
            "tokenomics": {"score": 75, "weight": 20, "factors": ["RPL 用于节点抵押"]},
            "operation": {"score": 80, "weight": 20, "factors": ["TVL 稳定增长"]},
        },
        "risk_warnings": ["节点运营商风险", "RPL 抵押要求"],
        "summary": "Rocket Pool 是去中心化程度最高的 ETH 质押协议，适合追求去中心化的用户。",
        "status": "published",
        "is_featured": True,
        "display_order": 2,
    },
    # 再质押
    {
        "name": "EigenLayer",
        "slug": "eigenlayer",
        "category": "restaking",
        "logo_url": "https://icons.llama.fi/eigenlayer.png",
        "website": "https://eigenlayer.xyz",
        "contract_address": "0x39053D51B77DC0d36036Fc1fCc8Cb819df8Ef37A",
        "defillama_id": "eigenlayer",
        "description": "EigenLayer 是以太坊再质押协议，允许用户通过再质押 ETH 为其他协议提供安全性并获取额外收益。",
        "overall_score": 75,
        "score_details": {
            "contract_security": {"score": 80, "weight": 35, "factors": ["已审计", "新协议需观察"]},
            "team": {"score": 85, "weight": 25, "factors": ["明星团队", "顶级投资"]},
            "tokenomics": {"score": 60, "weight": 20, "factors": ["EIGEN 代币已发布"]},
            "operation": {"score": 78, "weight": 20, "factors": ["TVL 快速增长"]},
        },
        "risk_warnings": ["新协议风险", "Slashing 风险叠加", "AVS 安全风险"],
        "summary": "EigenLayer 是再质押领域领导者，有顶级团队和投资，但作为新协议需要关注智能合约风险。",
        "status": "published",
        "is_featured": True,
        "display_order": 3,
    },
    # 借贷协议
    {
        "name": "Aave V3",
        "slug": "aave-v3",
        "category": "lending",
        "logo_url": "https://icons.llama.fi/aave-v3.png",
        "website": "https://aave.com",
        "contract_address": "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
        "defillama_id": "aave-v3",
        "description": "Aave 是领先的去中心化借贷协议，V3 版本引入了跨链功能和改进的风险管理。",
        "tokens": [{"symbol": "AAVE", "address": "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9"}],
        "overall_score": 88,
        "score_details": {
            "contract_security": {"score": 92, "weight": 35, "factors": ["久经考验", "多次审计", "Bug Bounty"]},
            "team": {"score": 90, "weight": 25, "factors": ["知名团队", "长期运营"]},
            "tokenomics": {"score": 85, "weight": 20, "factors": ["AAVE 治理代币成熟"]},
            "operation": {"score": 85, "weight": 20, "factors": ["TVL 稳定", "多链部署"]},
        },
        "risk_warnings": ["借贷利率波动", "清算风险"],
        "summary": "Aave 是最成熟的 DeFi 借贷协议之一，安全性高，但用户需注意借贷风险和清算机制。",
        "source_links": [
            {"type": "docs", "title": "官方文档", "url": "https://docs.aave.com"},
            {"type": "github", "title": "GitHub", "url": "https://github.com/aave"},
        ],
        "status": "published",
        "is_featured": True,
        "display_order": 4,
    },
    {
        "name": "Compound V3",
        "slug": "compound-v3",
        "category": "lending",
        "logo_url": "https://icons.llama.fi/compound-v3.png",
        "website": "https://compound.finance",
        "contract_address": "0xc3d688B66703497DAA19211EEdff47f25384cdc3",
        "defillama_id": "compound-v3",
        "description": "Compound V3 (Comet) 是 Compound 的最新版本，采用单一抵押品模式，专注于安全和效率。",
        "tokens": [{"symbol": "COMP", "address": "0xc00e94Cb662C3520282E6f5717214004A7f26888"}],
        "overall_score": 85,
        "score_details": {
            "contract_security": {"score": 90, "weight": 35, "factors": ["久经考验", "简化设计"]},
            "team": {"score": 88, "weight": 25, "factors": ["Compound Labs"]},
            "tokenomics": {"score": 80, "weight": 20, "factors": ["COMP 治理"]},
            "operation": {"score": 82, "weight": 20, "factors": ["稳定运营"]},
        },
        "risk_warnings": ["单一抵押品限制", "利率波动"],
        "summary": "Compound V3 采用更安全的单一抵押品设计，适合保守型用户。",
        "status": "published",
        "is_featured": False,
        "display_order": 5,
    },
    # DEX
    {
        "name": "Uniswap V3",
        "slug": "uniswap-v3",
        "category": "dex",
        "logo_url": "https://icons.llama.fi/uniswap.png",
        "website": "https://uniswap.org",
        "contract_address": "0x1F98431c8aD98523631AE4a59f267346ea31F984",
        "defillama_id": "uniswap-v3",
        "description": "Uniswap 是最大的去中心化交易所，V3 版本引入了集中流动性，提高资本效率。",
        "tokens": [{"symbol": "UNI", "address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"}],
        "overall_score": 90,
        "score_details": {
            "contract_security": {"score": 95, "weight": 35, "factors": ["久经考验", "开源", "多次审计"]},
            "team": {"score": 92, "weight": 25, "factors": ["Uniswap Labs", "行业领导者"]},
            "tokenomics": {"score": 85, "weight": 20, "factors": ["UNI 治理成熟"]},
            "operation": {"score": 90, "weight": 20, "factors": ["交易量最大", "多链部署"]},
        },
        "risk_warnings": ["无常损失", "MEV 攻击风险"],
        "summary": "Uniswap 是 DeFi 基础设施级别的 DEX，安全性极高，但 LP 需注意无常损失。",
        "status": "published",
        "is_featured": True,
        "display_order": 6,
    },
    {
        "name": "Curve Finance",
        "slug": "curve-finance",
        "category": "dex",
        "logo_url": "https://icons.llama.fi/curve.png",
        "website": "https://curve.fi",
        "contract_address": "0xD51a44d3FaE010294C616388b506AcdA1bfAAE46",
        "defillama_id": "curve-dex",
        "description": "Curve 是专注于稳定币和锚定资产交易的 DEX，提供低滑点交易。",
        "tokens": [{"symbol": "CRV", "address": "0xD533a949740bb3306d119CC777fa900bA034cd52"}],
        "overall_score": 82,
        "score_details": {
            "contract_security": {"score": 85, "weight": 35, "factors": ["长期运营", "复杂但稳定"]},
            "team": {"score": 75, "weight": 25, "factors": ["匿名创始人"]},
            "tokenomics": {"score": 80, "weight": 20, "factors": ["veCRV 机制复杂但有效"]},
            "operation": {"score": 85, "weight": 20, "factors": ["稳定币交易量大"]},
        },
        "risk_warnings": ["智能合约复杂", "veCRV 锁定风险"],
        "summary": "Curve 是稳定币交易的首选，低滑点优势明显，但 CRV 代币经济较复杂。",
        "status": "published",
        "is_featured": True,
        "display_order": 7,
    },
    # 收益优化
    {
        "name": "Pendle",
        "slug": "pendle",
        "category": "yield",
        "logo_url": "https://icons.llama.fi/pendle.png",
        "website": "https://pendle.finance",
        "contract_address": "0x0c880f6761F1af8d9Aa9C466984b80DAb9a8c9e8",
        "defillama_id": "pendle",
        "description": "Pendle 是收益代币化协议，允许用户交易未来收益，实现固定收益或杠杆收益策略。",
        "tokens": [{"symbol": "PENDLE", "address": "0x808507121B80c02388fAd14726482e061B8da827"}],
        "overall_score": 78,
        "score_details": {
            "contract_security": {"score": 80, "weight": 35, "factors": ["已审计", "创新设计"]},
            "team": {"score": 78, "weight": 25, "factors": ["团队公开"]},
            "tokenomics": {"score": 75, "weight": 20, "factors": ["PENDLE 代币"]},
            "operation": {"score": 80, "weight": 20, "factors": ["TVL 快速增长"]},
        },
        "risk_warnings": ["复杂机制", "PT/YT 价格波动"],
        "summary": "Pendle 提供创新的收益代币化方案，适合高级用户进行收益策略。",
        "status": "published",
        "is_featured": True,
        "display_order": 8,
    },
    # 稳定币
    {
        "name": "MakerDAO",
        "slug": "makerdao",
        "category": "stablecoin",
        "logo_url": "https://icons.llama.fi/makerdao.png",
        "website": "https://makerdao.com",
        "contract_address": "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2",
        "defillama_id": "makerdao",
        "description": "MakerDAO 是最大的去中心化稳定币协议，通过抵押资产铸造 DAI 稳定币。",
        "tokens": [
            {"symbol": "DAI", "address": "0x6B175474E89094C44Da98b954EescdeCB5BE1a85"},
            {"symbol": "MKR", "address": "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2"},
        ],
        "overall_score": 85,
        "score_details": {
            "contract_security": {"score": 90, "weight": 35, "factors": ["久经考验", "多次审计"]},
            "team": {"score": 85, "weight": 25, "factors": ["长期运营", "DAO 治理"]},
            "tokenomics": {"score": 82, "weight": 20, "factors": ["MKR 治理成熟"]},
            "operation": {"score": 85, "weight": 20, "factors": ["DAI 广泛采用"]},
        },
        "risk_warnings": ["清算风险", "USDC 敞口"],
        "summary": "MakerDAO 是最成熟的去中心化稳定币协议，DAI 被广泛采用，但需注意清算机制。",
        "status": "published",
        "is_featured": True,
        "display_order": 9,
    },
    # DEX 聚合器
    {
        "name": "1inch",
        "slug": "1inch",
        "category": "dex-aggregator",
        "logo_url": "https://icons.llama.fi/1inch-network.png",
        "website": "https://1inch.io",
        "contract_address": "0x1111111254EEB25477B68fb85Ed929f73A960582",
        "defillama_id": "1inch-network",
        "description": "1inch 是领先的 DEX 聚合器，通过智能路由为用户找到最优交易路径。",
        "tokens": [{"symbol": "1INCH", "address": "0x111111111117dC0aa78b770fA6A738034120C302"}],
        "overall_score": 83,
        "score_details": {
            "contract_security": {"score": 85, "weight": 35, "factors": ["已审计", "路由合约"]},
            "team": {"score": 85, "weight": 25, "factors": ["团队公开", "持续开发"]},
            "tokenomics": {"score": 78, "weight": 20, "factors": ["1INCH 治理"]},
            "operation": {"score": 85, "weight": 20, "factors": ["交易量大", "多链支持"]},
        },
        "risk_warnings": ["依赖底层 DEX", "路由可能非最优"],
        "summary": "1inch 是最常用的 DEX 聚合器，适合大额交易获得最优价格。",
        "status": "published",
        "is_featured": True,
        "display_order": 10,
    },
]
